{"@t":"2020-11-04T12:38:12.3591396Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[TempFileCleanup] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":44,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:38:12.3601390Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[HealthCheckNotifier] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":99,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:38:12.3601390Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[ServerInstProcess] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":20,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:38:12.3641376Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[Umbraco.Web.Scheduling.IBackgroundTask] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:38:12.3651372Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[RebuildIndexesOnStartup] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":60,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:38:12.3301378Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"Umbraco_freak_","HostingApplicationID":"/LM/W3SVC/2/ROOT","HostingPhysicalPath":"C:\\workspace\\Umbraco\\freak\\Umbraco_freak_\\","MachineName":"LAPTOP-TC3SQ9Q6","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:12.4391409Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:12.4441387Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:12.5011382Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[ScheduledTasks] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":31,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:38:12.5131364Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[LogScrubber] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:38:12.5141365Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[KeepAlive] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":39,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:38:12.5731391Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[ScheduledPublishing] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":98,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:38:12.5731391Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[ServerRegistration] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":25,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:38:12.7311364Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Resolving composer types.","TimingId":"d795f03","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:12.8121378Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Resolved.","Duration":80,"TimingId":"d795f03","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:14.9021366Z","@mt":"Registered with MainDom, localContentDbExists? {LocalContentDbExists}, localMediaDbExists? {LocalMediaDbExists}","LocalContentDbExists":true,"LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:14.9021366Z","@mt":"Creating the content store, localContentDbExists? {LocalContentDbExists}","LocalContentDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:14.9091369Z","@mt":"Creating the media store, localMediaDbExists? {LocalMediaDbExists}","LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:15.4781353Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading content from local cache file","TimingId":"e6d9a36","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:15.5101350Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":32,"TimingId":"e6d9a36","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:15.5251354Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from local cache file","TimingId":"58a3465","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:15.5251354Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":0,"TimingId":"58a3465","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:15.6841368Z","@mt":"Profiler is VoidProfiler, not profiling (must run debug mode to profile).","SourceContext":"Umbraco.Web.Logging.WebProfilerComponent","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:16.0231329Z","@mt":"Initializing Umbraco internal event handlers for cache refreshing.","SourceContext":"Umbraco.Web.Cache.DistributedCacheBinderComponent","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:16.0741373Z","@mt":"Adding examine event handlers for {RegisteredIndexers} index providers.","RegisteredIndexers":3,"SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:16.1071355Z","@mt":"Starting initialize async background thread.","SourceContext":"Umbraco.Web.Search.BackgroundIndexRebuilder","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:16.1131344Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Booted.","Duration":3814,"TimingId":"7760b1d","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":106,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"d26d55d2-5ee6-4e03-a8fe-e243a3ba7cc7"}
{"@t":"2020-11-04T12:38:16.5128879Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":39,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"99a9d692-abc8-4999-b1a5-97d43ee3d0f8"}
{"@t":"2020-11-04T12:38:16.5148867Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":39,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"99a9d692-abc8-4999-b1a5-97d43ee3d0f8"}
{"@t":"2020-11-04T12:38:40.7142465Z","@mt":"Application shutdown. Details: {ShutdownReason}\r\n\r\n_shutDownMessage={ShutdownMessage}\r\n\r\n_shutDownStack={ShutdownStack}","ShutdownReason":"MaxRecompilationsReached","ShutdownMessage":"Recompilation limit of 50 reached\r\nHostingEnvironment initiated shutdown\r\nHostingEnvironment caused shutdown","ShutdownStack":"   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)\r\n   at System.Environment.get_StackTrace()\r\n   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()\r\n   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()\r\n   at System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)\r\n   at System.Web.Compilation.DiskBuildResultCache.ShutdownCallBack(Object state)\r\n   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()\r\n   at System.Threading.ThreadPoolWorkQueue.Dispatch()\r\n   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()","SourceContext":"Umbraco.Web.UmbracoApplicationBase","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":20,"AppDomainId":3,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:21.1387885Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T12:41:41.2615494Z","@mt":"Scheduled health check results:","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2615494Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Folder & File Permissions","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Folder & File Permissions","HealthCheckResult":"Success","HealthCheckMessage":"All folders have the correct permissions set.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Folder & File Permissions","HealthCheckResult":"Success","HealthCheckMessage":"All files have the correct permissions set.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"SMTP Settings","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"SMTP Settings","HealthCheckResult":"Error","HealthCheckMessage":"In the Web.config file system.net/mailsettings section, the host is not configured.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Macro errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Macro errors","HealthCheckResult":"Error","HealthCheckMessage":"MacroErrors are set to 'throw' which will prevent some or all pages in your site from loading completely if there are any errors in macros. Rectifying this will set the value to 'inline'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Notification Email Settings","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Notification Email Settings","HealthCheckResult":"Error","HealthCheckMessage":"Notification email is still set to the default value of <strong>your@email.here</strong>.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Try Skip IIS Custom Errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Try Skip IIS Custom Errors","HealthCheckResult":"Success","HealthCheckMessage":"Try Skip IIS Custom Errors is set to 'true' and you're using IIS version '10.0'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Custom Errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Custom Errors","HealthCheckResult":"Success","HealthCheckMessage":"Custom errors are set to 'RemoteOnly'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Trace Mode","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Trace Mode","HealthCheckResult":"Success","HealthCheckMessage":"Trace mode is disabled.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Debug Compilation Mode","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Debug Compilation Mode","HealthCheckResult":"Success","HealthCheckMessage":"Debug compilation mode is disabled.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Cross-site scripting Protection (X-XSS-Protection header)","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Cross-site scripting Protection (X-XSS-Protection header)","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Cookie hijacking and protocol downgrade attacks Protection (Strict-Transport-Security Header (HSTS))","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Cookie hijacking and protocol downgrade attacks Protection (Strict-Transport-Security Header (HSTS))","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Content/MIME Sniffing Protection","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Content/MIME Sniffing Protection","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Excessive Headers","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Excessive Headers","HealthCheckResult":"Warning","HealthCheckMessage":"[httpsCheckInvalidUrl]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Click-Jacking Protection","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Click-Jacking Protection","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"HTTPS Configuration","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Error","HealthCheckMessage":"You are currently not viewing the site using the HTTPS scheme.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Info","HealthCheckMessage":"The appSetting 'Umbraco.Core.UseHttps' is set to 'false' in your web.config file. Once you access this site using the HTTPS scheme, that should be set to 'true'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL https://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Database data integrity check","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Database data integrity check","HealthCheckResult":"Success","HealthCheckMessage":"<p>All document paths are valid</p>\r\n","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:41:41.2625484Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Database data integrity check","HealthCheckResult":"Success","HealthCheckMessage":"<p>All media paths are valid</p>\r\n","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":27,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T12:46:25.1602700Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":92,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T12:51:29.1738552Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T12:56:33.1856249Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":93,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:01:37.2029481Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":91,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:06:41.9461243Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":92,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:11:45.9673152Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":91,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:16:49.9887816Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":92,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:21:54.0064587Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":92,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:26:58.0400984Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:32:02.0567850Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":91,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:37:06.0965857Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:39:48.2222093Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username mattiasp@hotmail.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":29,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"7c4d550c-413b-4980-a921-3b4c3bacd7a1"}
{"@t":"2020-11-04T13:39:48.2252089Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: mattiasp@hotmail.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":29,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"7c4d550c-413b-4980-a921-3b4c3bacd7a1"}
{"@t":"2020-11-04T13:42:10.1080674Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":92,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:47:14.1353490Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":91,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:52:18.1723144Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":93,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:57:22.2032292Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":11,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T13:59:17.2254824Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: mattiasp@hotmail.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":10,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":4,"HttpRequestId":"fb74b5e2-a07c-4b77-8c91-421033e16b2e"}
{"@t":"2020-11-04T13:59:23.2467050Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: mattiasp@hotmail.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":82,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":5,"HttpRequestId":"7a5b4ae9-1042-4840-9b4b-2ce4ce01b580"}
{"@t":"2020-11-04T13:59:58.5846290Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username mattiasp@hotmail.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":103,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"1537703f-9208-4039-ae72-342ed56cbdab"}
{"@t":"2020-11-04T13:59:58.5846290Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: mattiasp@hotmail.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":103,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"1537703f-9208-4039-ae72-342ed56cbdab"}
{"@t":"2020-11-04T14:02:26.2298472Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":92,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T14:07:30.2491461Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":94,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T14:12:34.2847224Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":86,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T14:17:38.3092810Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":94,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T14:22:42.3383022Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T14:27:46.3732160Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":90,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T14:32:50.3971395Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":88,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T14:37:54.4258492Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":89,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T14:42:58.4663561Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":89,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T14:48:02.4948940Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T14:51:43.2521816Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: mattiasp@hotmail.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":96,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":7,"HttpRequestId":"1e80cd03-846c-46d0-b63a-4dc0a0125ca9"}
{"@t":"2020-11-04T14:52:14.8816661Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username mattiasp@hotmail.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":8,"HttpRequestId":"27449dd7-b6c8-453f-bf2d-c7e96a275d3d"}
{"@t":"2020-11-04T14:52:14.8816661Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: mattiasp@hotmail.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":8,"HttpRequestId":"27449dd7-b6c8-453f-bf2d-c7e96a275d3d"}
{"@t":"2020-11-04T14:53:06.5139652Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":90,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T14:58:10.5499797Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":91,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T15:03:14.5696585Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":89,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T15:08:18.5857776Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":81,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T15:11:50.2422392Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: mattiasp@hotmail.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":44,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":9,"HttpRequestId":"4ec60863-1073-478d-94c6-0019484799e7"}
{"@t":"2020-11-04T15:13:22.6179921Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":87,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T15:18:26.6416260Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":88,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T15:23:30.6725303Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":81,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T15:26:15.9697958Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username mattiasp@hotmail.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":96,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":10,"HttpRequestId":"bb0a7219-30f1-4eb5-81fa-72ef52809ad3"}
{"@t":"2020-11-04T15:26:15.9697958Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: mattiasp@hotmail.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":96,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":10,"HttpRequestId":"bb0a7219-30f1-4eb5-81fa-72ef52809ad3"}
{"@t":"2020-11-04T15:28:34.7050196Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":94,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T15:33:38.7153945Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":87,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T15:38:42.7450451Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":86,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T15:43:46.7693378Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":85,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T15:48:50.7821148Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":87,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T15:53:54.9334361Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":91,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T15:58:18.9845811Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: mattiasp@hotmail.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":64,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":11,"HttpRequestId":"3cda82ec-d5c8-4a48-964f-5699b149fe1c"}
{"@t":"2020-11-04T15:58:24.2591040Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: mattiasp@hotmail.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":12,"HttpRequestId":"5f318f02-dfaf-47c4-998f-b68d0f05e0a7"}
{"@t":"2020-11-04T15:58:58.9503709Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":86,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T16:04:02.9823851Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":81,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T16:09:07.0092683Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":81,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T16:14:11.0424741Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T16:19:15.0656632Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":70,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T16:24:19.0957594Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":54,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T16:25:33.2318352Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username mattiasp@hotmail.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":102,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":13,"HttpRequestId":"5bfe3690-1c6b-4057-94e3-b1ec384a4d90"}
{"@t":"2020-11-04T16:25:33.2318352Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: mattiasp@hotmail.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":102,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":13,"HttpRequestId":"5bfe3690-1c6b-4057-94e3-b1ec384a4d90"}
{"@t":"2020-11-04T16:29:23.1258295Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":61,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T16:34:27.1472072Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T16:38:43.8996602Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username mattiasp@hotmail.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":87,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":14,"HttpRequestId":"da1593c9-ad05-43c8-bd4f-1ce5bbf032ac"}
{"@t":"2020-11-04T16:38:43.8996602Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: mattiasp@hotmail.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":87,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":14,"HttpRequestId":"da1593c9-ad05-43c8-bd4f-1ce5bbf032ac"}
{"@t":"2020-11-04T16:39:31.1725844Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":76,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T16:44:35.2005628Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T16:49:39.2257973Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":24,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T16:54:43.2476205Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":8,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T16:58:14.2190961Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: mattiasp@hotmail.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":28,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":15,"HttpRequestId":"972759b6-230b-41c4-8ae6-ea78b0ae462f"}
{"@t":"2020-11-04T16:58:17.2458951Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: mattiasp@hotmail.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":68,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":16,"HttpRequestId":"92a7d9af-b14b-498c-8937-3cec07142ad8"}
{"@t":"2020-11-04T16:59:47.2659072Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":84,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T17:04:51.2869518Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":77,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T17:09:55.3233153Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":97,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T17:10:29.6666868Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username mattiasp@hotmail.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":90,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":17,"HttpRequestId":"210591ab-1c73-47ff-bf7e-44c1b472c66f"}
{"@t":"2020-11-04T17:10:29.6676864Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: mattiasp@hotmail.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":90,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":17,"HttpRequestId":"210591ab-1c73-47ff-bf7e-44c1b472c66f"}
{"@t":"2020-11-04T17:14:59.3579932Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":19,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T17:20:03.3806111Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":23,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T17:23:34.7393513Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username mattiasp@hotmail.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":85,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":18,"HttpRequestId":"3d33bda5-61f9-4b52-84e6-cca729784ea9"}
{"@t":"2020-11-04T17:23:34.7393513Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: mattiasp@hotmail.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":85,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":18,"HttpRequestId":"3d33bda5-61f9-4b52-84e6-cca729784ea9"}
{"@t":"2020-11-04T17:24:00.7444754Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"Login attempt succeeded for username mattiasp@hotmail.com from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":14,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":19,"HttpRequestId":"f499ff40-5744-4020-95fe-cefffdda19be"}
{"@t":"2020-11-04T17:24:00.7444754Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User: mattiasp@hotmail.com logged in from IP address ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":14,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":19,"HttpRequestId":"f499ff40-5744-4020-95fe-cefffdda19be"}
{"@t":"2020-11-04T17:25:07.4154587Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":23,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T17:30:11.4473373Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":79,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T17:35:15.4892481Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":80,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T17:40:19.5109547Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":21,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T17:45:23.5512845Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":79,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T17:47:48.1662955Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[TempFileCleanup] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.1672993Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[HealthCheckNotifier] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.1672993Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[ScheduledTasks] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.1672993Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[Umbraco.Web.Scheduling.IBackgroundTask] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.1832970Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[ScheduledTasks] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":53,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.1832970Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[Umbraco.Web.Scheduling.IBackgroundTask] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":93,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.1902977Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[LogScrubber] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.1932949Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[ServerRegistration] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.1932949Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[ScheduledPublishing] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.1932949Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[RebuildIndexesOnStartup] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.1952959Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[KeepAlive] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2002965Z","@mt":"Stopping ({SignalSource})","SignalSource":"environment","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2072968Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[Umbraco.Web.Scheduling.IBackgroundTask] ","TaskStatus":"cancelled","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":93,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2092950Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[ScheduledTasks] ","TaskStatus":"cancelled","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":53,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2142961Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[TempFileCleanup] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":14,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2142961Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[TempFileCleanup] ","TaskStatus":"cancelled","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":14,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2142961Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[RebuildIndexesOnStartup] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":14,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2142961Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[RebuildIndexesOnStartup] ","TaskStatus":"cancelled","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":14,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2142961Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[ServerRegistration] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":65,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2142961Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[ServerRegistration] ","TaskStatus":"cancelled","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":65,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2142961Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[ScheduledPublishing] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2142961Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[ScheduledPublishing] ","TaskStatus":"cancelled","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2142961Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[LogScrubber] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2142961Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[LogScrubber] ","TaskStatus":"cancelled","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2142961Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[KeepAlive] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2142961Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[KeepAlive] ","TaskStatus":"cancelled","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":56,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2252969Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[HealthCheckNotifier] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":85,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.2252969Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[HealthCheckNotifier] ","TaskStatus":"cancelled","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":85,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.3262949Z","@mt":"Released from MainDom","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.3322952Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Examine shutting down","TimingId":"4f8a119","SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.3552946Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":23,"TimingId":"4f8a119","SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.3562957Z","@mt":"Released ({SignalSource})","SignalSource":"environment","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.3562957Z","@mt":"{LogPrefix} Terminating {Immediate}","LogPrefix":"[ServerInstProcess] ","Immediate":"","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.3832955Z","@mt":"{LogPrefix} Canceling tasks","LogPrefix":"[ServerInstProcess] ","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":75,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.3832955Z","@mt":"{LogPrefix} Tasks {TaskStatus}, terminated","LogPrefix":"[ServerInstProcess] ","TaskStatus":"cancelled","SourceContext":"Umbraco.Web.Scheduling.BackgroundTaskRunner","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":75,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:48.4973154Z","@mt":"Application shutdown. Details: {ShutdownReason}\r\n\r\n_shutDownMessage={ShutdownMessage}\r\n\r\n_shutDownStack={ShutdownStack}","ShutdownReason":"MaxRecompilationsReached","ShutdownMessage":"Recompilation limit of 50 reached\r\nHostingEnvironment initiated shutdown\r\nHostingEnvironment caused shutdown","ShutdownStack":"   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)\r\n   at System.Environment.get_StackTrace()\r\n   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()\r\n   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()\r\n   at System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)\r\n   at System.Web.Compilation.DiskBuildResultCache.ShutdownCallBack(Object state)\r\n   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()\r\n   at System.Threading.ThreadPoolWorkQueue.Dispatch()\r\n   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()","SourceContext":"Umbraco.Web.UmbracoApplicationBase","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":22,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:47:50.7382939Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Booting Umbraco 8.9.0.","TimingId":"6b7991d","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:50.7542931Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"Umbraco_freak_","HostingApplicationID":"/LM/W3SVC/2/ROOT","HostingPhysicalPath":"C:\\workspace\\Umbraco\\freak\\Umbraco_freak_\\","MachineName":"LAPTOP-TC3SQ9Q6","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:50.8022953Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:50.8032939Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:51.0192938Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Resolving composer types.","TimingId":"b388458","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:51.1192953Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Resolved.","Duration":99,"TimingId":"b388458","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:53.1289712Z","@mt":"Registered with MainDom, localContentDbExists? {LocalContentDbExists}, localMediaDbExists? {LocalMediaDbExists}","LocalContentDbExists":true,"LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:53.1289712Z","@mt":"Creating the content store, localContentDbExists? {LocalContentDbExists}","LocalContentDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:53.1329728Z","@mt":"Creating the media store, localMediaDbExists? {LocalMediaDbExists}","LocalMediaDbExists":true,"SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:53.5999704Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading content from local cache file","TimingId":"81b236d","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:53.6449722Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":44,"TimingId":"81b236d","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:53.6639783Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Loading media from local cache file","TimingId":"e68d9c7","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:53.6639783Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Completed.","Duration":0,"TimingId":"e68d9c7","SourceContext":"Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:53.7639731Z","@mt":"Profiler is VoidProfiler, not profiling (must run debug mode to profile).","SourceContext":"Umbraco.Web.Logging.WebProfilerComponent","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:53.9869756Z","@mt":"Initializing Umbraco internal event handlers for cache refreshing.","SourceContext":"Umbraco.Web.Cache.DistributedCacheBinderComponent","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:54.0579856Z","@mt":"Adding examine event handlers for {RegisteredIndexers} index providers.","RegisteredIndexers":3,"SourceContext":"Umbraco.Web.Search.ExamineComponent","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:54.1049694Z","@mt":"Starting initialize async background thread.","SourceContext":"Umbraco.Web.Search.BackgroundIndexRebuilder","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:54.1059721Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Booted.","Duration":3387,"TimingId":"6b7991d","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":78,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"74745364-9c85-4d3a-a7c4-813b3f5b94ad"}
{"@t":"2020-11-04T17:47:54.4519702Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":65,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"a070f26b-b3b3-4594-8bee-86d55290af69"}
{"@t":"2020-11-04T17:47:54.4519702Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://localhost/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":85,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"a95a2fdc-a320-4222-8d58-56cf43305261"}
{"@t":"2020-11-04T17:47:54.4539743Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":85,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":3,"HttpRequestId":"a95a2fdc-a320-4222-8d58-56cf43305261"}
{"@t":"2020-11-04T17:47:54.4539743Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":65,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"a070f26b-b3b3-4594-8bee-86d55290af69"}
{"@t":"2020-11-04T17:50:59.1810310Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":13,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T17:51:19.2803508Z","@mt":"Scheduled health check results:","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Folder & File Permissions","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Folder & File Permissions","HealthCheckResult":"Success","HealthCheckMessage":"All folders have the correct permissions set.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Folder & File Permissions","HealthCheckResult":"Success","HealthCheckMessage":"All files have the correct permissions set.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"SMTP Settings","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"SMTP Settings","HealthCheckResult":"Error","HealthCheckMessage":"In the Web.config file system.net/mailsettings section, the host is not configured.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Macro errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Macro errors","HealthCheckResult":"Error","HealthCheckMessage":"MacroErrors are set to 'throw' which will prevent some or all pages in your site from loading completely if there are any errors in macros. Rectifying this will set the value to 'inline'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Notification Email Settings","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Notification Email Settings","HealthCheckResult":"Error","HealthCheckMessage":"Notification email is still set to the default value of <strong>your@email.here</strong>.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Try Skip IIS Custom Errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Try Skip IIS Custom Errors","HealthCheckResult":"Success","HealthCheckMessage":"Try Skip IIS Custom Errors is set to 'true' and you're using IIS version '10.0'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Custom Errors","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Custom Errors","HealthCheckResult":"Success","HealthCheckMessage":"Custom errors are set to 'RemoteOnly'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Trace Mode","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Trace Mode","HealthCheckResult":"Success","HealthCheckMessage":"Trace mode is disabled.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Debug Compilation Mode","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Debug Compilation Mode","HealthCheckResult":"Success","HealthCheckMessage":"Debug compilation mode is disabled.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Cross-site scripting Protection (X-XSS-Protection header)","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Cross-site scripting Protection (X-XSS-Protection header)","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Cookie hijacking and protocol downgrade attacks Protection (Strict-Transport-Security Header (HSTS))","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T17:51:19.2813506Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Cookie hijacking and protocol downgrade attacks Protection (Strict-Transport-Security Header (HSTS))","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Content/MIME Sniffing Protection","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Content/MIME Sniffing Protection","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Excessive Headers","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Excessive Headers","HealthCheckResult":"Warning","HealthCheckMessage":"[httpsCheckInvalidUrl]","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"Click-Jacking Protection","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Click-Jacking Protection","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL http://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Checks for '{HealthCheckName}' completed with errors.","@l":"Warning","HealthCheckName":"HTTPS Configuration","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"WARN "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Error","HealthCheckMessage":"You are currently not viewing the site using the HTTPS scheme.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Info","HealthCheckMessage":"The appSetting 'Umbraco.Core.UseHttps' is set to 'false' in your web.config file. Once you access this site using the HTTPS scheme, that should be set to 'true'.","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"HTTPS Configuration","HealthCheckResult":"Error","HealthCheckMessage":"Error pinging the URL https://localhost/umbraco - 'Unable to connect to the remote server'","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Checks for '{HealthCheckName}' all completed successfully.","HealthCheckName":"Database data integrity check","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Database data integrity check","HealthCheckResult":"Success","HealthCheckMessage":"<p>All document paths are valid</p>\r\n","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:51:19.2823527Z","@mt":"Result for {HealthCheckName}: {HealthCheckResult}, Message: '{HealthCheckMessage}'","HealthCheckName":"Database data integrity check","HealthCheckResult":"Success","HealthCheckMessage":"<p>All media paths are valid</p>\r\n","SourceContext":"Umbraco.Web.HealthCheck.HealthCheckResults","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":74,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO "}
{"@t":"2020-11-04T17:56:03.2080345Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T18:01:07.2315658Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":23,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T18:06:08.3905036Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: mattiasp@hotmail.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":65,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":4,"HttpRequestId":"6a8d5f79-a0c6-4a47-901a-209a63a2cfd7"}
{"@t":"2020-11-04T18:06:09.3575605Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: mattiasp@hotmail.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":53,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":5,"HttpRequestId":"6e5d070e-bf52-4bbd-8f44-1888f5177e3f"}
{"@t":"2020-11-04T18:06:11.8020818Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":13,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T18:06:15.3853606Z","@mt":"[{EventType}] Event Id: {EventId}, State: {State}","EventType":"Information","EventId":0,"State":"User logged will be logged out due to timeout: mattiasp@hotmail.com, IP Address: ::1","SourceContext":"Umbraco.Core.Logging.OwinLogger","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":65,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"b8b2299a-0aeb-4863-a937-3bdb17e05696"}
{"@t":"2020-11-04T18:11:15.8350171Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":87,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T18:16:19.8631514Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":40,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T18:21:23.8811617Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":32,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
{"@t":"2020-11-04T18:26:27.9102783Z","@mt":"Keep alive failed (at '{keepAlivePingUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:80\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- End of inner exception stack trace ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__5.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 69","keepAlivePingUrl":"http://localhost/umbraco/api/keepalive/ping","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":19324,"ProcessName":"iisexpress","ThreadId":54,"AppDomainId":5,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"LAPTOP-TC3SQ9Q6","Log4NetLevel":"ERROR"}
